export const UserRows = [
    { id: 1, lastName: 'Snow', firstName: 'Jon', email: 'jonSnow@gmail.com'},
    { id: 2, lastName: 'Lannister', firstName: 'Cersei', email: 42 },
    { id: 3, lastName: 'Lannister', firstName: 'Jaime', email: 45 },
    { id: 4, lastName: 'Stark', firstName: 'Arya', email: 16 },
    { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', email: null },
    { id: 6, lastName: 'Melisandre', firstName: null, email: 150 },
    { id: 7, lastName: 'Clifford', firstName: 'Ferrara', email: 44 },
    { id: 8, lastName: 'Frances', firstName: 'Rossini', email: 36 },
    { id: 9, lastName: 'Roxie', firstName: 'Harvey', email: 65 },
    { id: 10, lastName: 'Roxie', firstName: 'Harvey', email: 65 },
    { id: 11, lastName: 'Roxie', firstName: 'Harvey', email: 65 },
    { id: 12, lastName: 'Roxie', firstName: 'Harvey', email: 65 },
    { id: 13, lastName: 'Roxie', firstName: 'Harvey', email: 65 },
  ];